apiVersion: v1
kind: Service
metadata:
  name: curl
  labels:
    app: curl
spec:
  ports:
    - port: 8008
      name: http
  selector:
    app: curl
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: curl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
spec:
  selector:
    matchLabels:
      app: curl
  replicas: 1
  template:
    metadata:
      labels:
        app: curl
    spec:
      serviceAccountName: curl
      containers:
        - name: curl
          image: radial/busyboxplus:curl
          command: ["/bin/sleep", "10000000"]
          imagePullPolicy: IfNotPresent
---
